import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';

/**
 * SQL migrations generated by drizzle-kit; same relative path from src/ and
 * dist/. Deliberately not `new URL('../../drizzle', import.meta.url)`:
 * that two-argument form is the standard "asset reference" pattern webpack
 * and Turbopack both statically scan for, and Turbopack tries to bundle the
 * referenced directory even when this module is never called - which
 * breaks any consumer that only imports other exports from this package's
 * barrel (e.g. apps/web) through `serverExternalPackages`, since Turbopack
 * still walks into "external" modules looking for asset references before
 * deciding to externalize them.
 */
export const MIGRATIONS_FOLDER = resolve(dirname(fileURLToPath(import.meta.url)), '../../drizzle');

/**
 * Applies pending migrations. Run explicitly (`pnpm db:migrate`, or the
 * compose `migrate` service), never implicitly on application startup.
 */
export async function runMigrations(url: string): Promise<void> {
  const client = postgres(url, { max: 1, onnotice: () => undefined });
  try {
    await migrate(drizzle({ client }), { migrationsFolder: MIGRATIONS_FOLDER });
  } finally {
    await client.end({ timeout: 5 });
  }
}
